# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Createpr < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/internetblacksmith/createpr/releases/download/v0.4.0/createpr_Darwin_x86_64.tar.gz"
      sha256 "f14afa3fd61b8ac569503d69824b1ba556ed1af28ae536af2a33d9c612bf8737"

      def install
        bin.install "createpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/internetblacksmith/createpr/releases/download/v0.4.0/createpr_Darwin_arm64.tar.gz"
      sha256 "24ae4cb63192362bd548b6cb0abd096cf802593151f13ce733574b1f524e97bb"

      def install
        bin.install "createpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/internetblacksmith/createpr/releases/download/v0.4.0/createpr_Linux_x86_64.tar.gz"
        sha256 "2f57f01139c821d2d821cd1253ca9c00ab013615d605b3a5f2ad037460257640"

        def install
          bin.install "createpr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/internetblacksmith/createpr/releases/download/v0.4.0/createpr_Linux_arm64.tar.gz"
        sha256 "327c98ef3163fec8db2ee7d9e4898b662652e8edd7453a388d60b2cb3dd5c886"

        def install
          bin.install "createpr"
        end
      end
    end
  end
end
